package io.specmatic.gradle.vuln.dto

import com.fasterxml.jackson.annotation.JsonProperty

// auto generated by github copilot. Don't ask :)

data class VulnerabilityReport(
    @field:JsonProperty("SchemaVersion") val schemaVersion: Int = 0,
    @field:JsonProperty("CreatedAt") val createdAt: String? = null,
    @field:JsonProperty("ArtifactName") val artifactName: String? = null,
    @field:JsonProperty("ArtifactType") val artifactType: String? = null,
    @field:JsonProperty("Results") val results: List<Result> = emptyList(),
)

data class Result(
    @field:JsonProperty("Target") val target: String? = null,
    @field:JsonProperty("Class") val clazz: String? = null,
    @field:JsonProperty("Type") val type: String? = null,
    @field:JsonProperty("Vulnerabilities") val vulnerabilities: List<Vulnerability> = emptyList(),
)

data class Vulnerability(
    @field:JsonProperty("VulnerabilityID") val vulnerabilityId: String? = null,
    @field:JsonProperty("PkgID") val pkgId: String? = null,
    @field:JsonProperty("PkgName") val pkgName: String? = null,
    @field:JsonProperty("PkgIdentifier") val pkgIdentifier: PkgIdentifier? = null,
    @field:JsonProperty("InstalledVersion") val installedVersion: String? = null,
    @field:JsonProperty("Status") val status: String? = null,
    @field:JsonProperty("SeveritySource") val severitySource: String? = null,
    @field:JsonProperty("PrimaryURL") val primaryUrl: String? = null,
    @field:JsonProperty("DataSource") val dataSource: DataSource? = null,
    @field:JsonProperty("Title") val title: String? = null,
    @field:JsonProperty("Description") val description: String? = null,
    @field:JsonProperty("Severity") val severity: String? = null,
    @field:JsonProperty("CweIDs") val cweIds: List<String> = emptyList(),
    @field:JsonProperty("VendorSeverity") val vendorSeverity: Map<String, Int> = emptyMap(),
    @field:JsonProperty("CVSS") val cvss: Map<String, Cvss> = emptyMap(),
    @field:JsonProperty("References") val references: List<String> = emptyList(),
    @field:JsonProperty("PublishedDate") val publishedDate: String? = null,
    @field:JsonProperty("LastModifiedDate") val lastModifiedDate: String? = null,
)

data class PkgIdentifier(
    @field:JsonProperty("PURL") val purl: String? = null,
    @field:JsonProperty("UID") val uid: String? = null,
    @field:JsonProperty("BOMRef") val bomRef: String? = null,
)

data class DataSource(
    @field:JsonProperty("ID") val id: String? = null,
    @field:JsonProperty("Name") val name: String? = null,
    @field:JsonProperty("URL") val url: String? = null,
)

data class Cvss(
    @field:JsonProperty("V3Vector") val v3Vector: String? = null,
    @field:JsonProperty("V3Score") val v3Score: Double? = null,
)
