name: Java Build with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is required so that the dependency check can push dependency graph to the github repository
    steps:
      - uses: znsio/specmatic-github-workflows/action-build-gradle@main
