name: Release Snapshot

on:
  workflow_run:
    workflows: [ "Java Build With Gradle" ]
    types:
      - completed

jobs:
  snapshot:
    needs: [ gradle ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: znsio/specmatic-github-workflows/action-gradle-post-build@main
        with:
          extra-gradle-args: "publishAllPublicationsToMavenCentralRepository"