name: Release Snapshot

on:
  workflow_run:
    workflows: [ "Java Build With Gradle" ]
    types:
      - completed

jobs:
  snapshot:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Create secrets file
        run: .github/populate-env-vars > ~/.specmatic-secrets
        env:
          SPECMATIC_MAVEN_CENTRAL_USERNAME: "${{ secrets.SPECMATIC_MAVEN_CENTRAL_USERNAME }}"
          SPECMATIC_MAVEN_CENTRAL_PASSWORD: "${{ secrets.SPECMATIC_MAVEN_CENTRAL_PASSWORD }}"
          SPECMATIC_GPG_PRIVATE_KEY: "${{ secrets.SPECMATIC_GPG_PRIVATE_KEY }}"
          SPECMATIC_GPG_KEY_ID: "${{ secrets.SPECMATIC_GPG_KEY_ID }}"
          SPECMATIC_GPG_PRIVATE_KEY_PASSPHRASE: "${{ secrets.SPECMATIC_GPG_PRIVATE_KEY_PASSPHRASE }}"
          SPECMATIC_GITHUB_USER: "${{ secrets.SPECMATIC_GITHUB_USER }}"
          SPECMATIC_GITHUB_TOKEN: "${{ secrets.SPECMATIC_GITHUB_TOKEN }}"

      - uses: znsio/specmatic-github-workflows/action-gradle-post-build@main
        with:
          gradle-extra-env-file: ~/.specmatic-secrets
          gradle-extra-args: publishAllPublicationsToMavenCentralRepository publishPluginMavenPublicationToSpecmaticPrivateRepository
          download-artifact-github-token: ${{ secrets.GITHUB_TOKEN }}
