name: Java Publish with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_run:
    workflows: [ "Java Build with Gradle" ]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is required so that the dependency check can push dependency graph to the github repository
    steps:
      - uses: znsio/specmatic-github-workflows/action-publish-gradle@main
