name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (from gradle.properties, without -SNAPSHOT)'
        required: true
      next_version:
        description: 'Next version (Ensure to add -SNAPSHOT)'
        required: true

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: echo "This is a dummy job to satisfy the requirement of having at least one job with no dependencies."

  release:
    needs: [ gradle-snapshot ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Create secrets file
        run: |
          echo "" > ~/.specmatic-secrets
          echo "export ORG_GRADLE_PROJECT_mavenCentralUsername='${{ secrets.SPECMATIC_MAVEN_CENTRAL_USERNAME }}'" >> ~/.specmatic-secrets
          echo "export ORG_GRADLE_PROJECT_mavenCentralPassword='${{ secrets.SPECMATIC_MAVEN_CENTRAL_PASSWORD }}'" >> ~/.specmatic-secrets
          echo "export ORG_GRADLE_PROJECT_signingInMemoryKey='${{ secrets.SPECMATIC_GPG_PRIVATE_KEY }}'" >> ~/.specmatic-secrets
          echo "export ORG_GRADLE_PROJECT_signingInMemoryKeyId='${{ secrets.SPECMATIC_GPG_KEY_ID }}'" >> ~/.specmatic-secrets
          echo "export ORG_GRADLE_PROJECT_signingInMemoryKeyPassword='${{ secrets.SPECMATIC_GPG_PRIVATE_KEY_PASSPHRASE }}'" >> ~/.specmatic-secrets
      - uses: znsio/specmatic-github-workflows/action-gradle-post-build@main
        with:
          gradle-extra-env-file: ~/.specmatic-secrets
          gradle-extra-args: release

      - uses: znsio/specmatic-github-workflows/action-gradle-post-build@main
        with:
          gradle-extra-env-file: ~/.specmatic-secrets
          gradle-extra-args: release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${{ github.event.inputs.release_version }} -Prelease.newVersion=${{ github.event.inputs.next_version }}