name: Release

on:
  workflow_run:
    workflows: [ "Java Build with Gradle" ]
    types:
      - completed

  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
      next_version:
        description: 'Next version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is required so that the dependency check can push dependency graph to the github repository
    steps:
      - uses: znsio/specmatic-github-workflows/action-release-gradle@main
        with:
          extra-gradle-args: -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${{ github.event.inputs.release_version }} -Prelease.newVersion=${{ github.event.inputs.next_version }}
