name: Java Publish with Gradle

on:
  workflow_run:
    workflows: [ "Java Build with Gradle" ]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is required so that the dependency check can push dependency graph to the github repository
    steps:
      - uses: znsio/specmatic-github-workflows/action-publish-gradle@main
        with:
          gradle-extra-args: "-Pgithub.actor=dummy -Pgithub.token=${{secrets.ACTIONS_REPO_RW_TOKEN}}"
