name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (from gradle.properties, without -SNAPSHOT)'
        required: true
      next_version:
        description: 'Next version (Ensure to add -SNAPSHOT)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create secrets file
        run: ruby ./.github/populate-env-vars > ~/.specmatic-secrets
        env:
          SPECMATIC_MAVEN_CENTRAL_USERNAME: "${{ secrets.SPECMATIC_MAVEN_CENTRAL_USERNAME }}"
          SPECMATIC_MAVEN_CENTRAL_PASSWORD: "${{ secrets.SPECMATIC_MAVEN_CENTRAL_PASSWORD }}"
          SPECMATIC_GPG_PRIVATE_KEY: "${{ secrets.SPECMATIC_GPG_PRIVATE_KEY }}"
          SPECMATIC_GPG_KEY_ID: "${{ secrets.SPECMATIC_GPG_KEY_ID }}"
          SPECMATIC_GPG_PRIVATE_KEY_PASSPHRASE: "${{ secrets.SPECMATIC_GPG_PRIVATE_KEY_PASSPHRASE }}"
          SPECMATIC_GITHUB_USER: "${{ secrets.SPECMATIC_GITHUB_USER }}"
          SPECMATIC_GITHUB_TOKEN: "${{ secrets.SPECMATIC_GITHUB_TOKEN }}"

      - uses: znsio/specmatic-github-workflows/action-gradle-post-build@main
        with:
          gradle-extra-env-file: ~/.specmatic-secrets
          download-artifact-github-token: ${{ secrets.GITHUB_TOKEN }}
          gradle-extra-args: >
            release
            -Prelease.useAutomaticVersion=true
            -Prelease.releaseVersion=${{ github.event.inputs.release_version }}
            -Prelease.newVersion=${{ github.event.inputs.next_version }}
            -Pgradle.publish.key=${{ secrets.SPECMATIC_GRADLE_PUBLISH_KEY }}
            -Pgradle.publish.secret=${{ secrets.SPECMATIC_GRADLE_PUBLISH_SECRET }}
          pre-gradle-command:  |
            git config --local user.email "github-service-account@specmatic.io"
            git config --local user.name "Specmatic GitHub Service Account"
            git clean -fd
