name: Java Build with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is required so that the dependency check can push dependency graph to the github repository
    steps:
      - name: 'Build/Test'
        uses: specmatic/specmatic-github-workflows/action-build-gradle@main

      - name: Publish Snapshot
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')
        run: ./gradlew publishAllPublicationsToMavenCentralRepository publishAllPublicationsToSpecmaticPrivateRepository publishAllPublicationsToSpecmaticSnapshotsRepository
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: "${{ secrets.SPECMATIC_MAVEN_CENTRAL_USERNAME }}"
          ORG_GRADLE_PROJECT_mavenCentralPassword: "${{ secrets.SPECMATIC_MAVEN_CENTRAL_PASSWORD }}"
          ORG_GRADLE_PROJECT_signingInMemoryKey: "${{ secrets.SPECMATIC_GPG_PRIVATE_KEY }}"
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: "${{ secrets.SPECMATIC_GPG_KEY_ID }}"
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: "${{ secrets.SPECMATIC_GPG_PRIVATE_KEY_PASSPHRASE }}"
          ORG_GRADLE_PROJECT_specmaticSnapshotsUsername: "${{ vars.SPECMATIC_GITHUB_USER }}"
          ORG_GRADLE_PROJECT_specmaticSnapshotsPassword: "${{ secrets.SPECMATIC_GITHUB_TOKEN }}"
          ORG_GRADLE_PROJECT_specmaticReleasesUsername: "${{ vars.SPECMATIC_GITHUB_USER }}"
          ORG_GRADLE_PROJECT_specmaticReleasesPassword: "${{ secrets.SPECMATIC_GITHUB_TOKEN }}"
          ORG_GRADLE_PROJECT_specmaticPrivateUsername: "${{ vars.SPECMATIC_GITHUB_USER }}"
          ORG_GRADLE_PROJECT_specmaticPrivatePassword: "${{ secrets.SPECMATIC_GITHUB_TOKEN }}"
          SPECMATIC_GITHUB_USER: "${{ vars.SPECMATIC_GITHUB_USER }}"
          SPECMATIC_GITHUB_TOKEN: "${{ secrets.SPECMATIC_GITHUB_TOKEN }}"
